name: analysis-essentials
channels:
  - conda-forge
dependencies:
  - boost-histogram
  - hep_ml
  - hepunits
  - hist
  - ipython
  - matplotlib
  - mplhep
  - nb_conda
  - nb_conda_kernels
  - notebook<7.0.0
  - numpy
  - pandas
  - particle
  - pandoc
  - pip
  - scikit-learn
  - scipy
  - uproot
  - uproot3
  - vector
  - wget
  - xgboost
  - zfit >=0.14.0
  - hepstats
  - pip:
    - git+https://github.com/hsf-training/python-lesson.git
    - formulate
    - starterkit-ci
